### ISSUE TITLE
After version 0.17.2, on netlify, Authkit always throws: You are calling 'withAuth' on a route that isn’t covered by the AuthKit middleware

### ISSUE THREAD

**Issue by spookyuser** [workos/authkit-nextjs#229]
**Describe the bug**

On I think any version after 0.17.2 but certainly above 1.0, If you call withAuth in a server component like so:

```
export default async function DashboardLayout({
  children
}: {
  children: React.ReactNode
}) {
  const auth = await withAuth({
    ensureSignedIn: true
  })

  return (
    <Providers userId={auth.user?.id}>
      <div className="h-[calc(100vh+2.75rem)]">
```

On netlify, Authkit will always throws this error:

`Error: You are calling 'withAuth' on a route that isn’t covered by the AuthKit middleware. Make sure it is running on all paths you are calling 'withAuth' from by updating your middleware config in 'middleware.(js|ts)'

When running locally it doesn't happen.

**To Reproduce**

Run the authkit nextjs example on netlify with an rsc component

**Expected behavior**

I expect to be able to call withAuth in server components like in 0.17.2 on netlify

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - authkit-nextjs version 2.2.0
 - Next.js version 15.2.3

**Additional context**
I think it could be related to this issue https://answers.netlify.com/t/nextjs-headers-set-in-middleware-not-available-on-layout-tsx-or-page-tsx/129098

Also if this is something netlify needs to fix that's totally fair

Also I think the key difference is here https://github.com/workos/authkit-nextjs/blame/1a6649e302fc24a112171c9c827d069c82b610fb/src/session.ts#L106 I think in 0.17  the headers were adjusted in the request not response by the middleware

**Comment by nicknisi** [comment]
Thanks for reporting! I was able to reproduce this on a Netlify deploy and am looking into it.

**Comment by spookyuser** [comment]
Thank you so much for the fast fix!

**Comment by nicknisi** [comment]
@spookyuser I had to revert this as it caused unintended issues. Will be looking into a better fix this week.

**Comment by spookyuser** [comment]
No worries :)

**Comment by OutThisLife** [comment]
I'm getting this locally on nextjs no matter what too. Fresh nextjs/workos install.

**Comment by nicknisi** [comment]
@OutThisLife Are you also deploying to Netlify when you see this isue?

**Comment by AnttiJalomaki** [comment]
> I'm getting this locally on nextjs no matter what too. Fresh nextjs/workos install.
> 
> UPDATE: nvm, if using `src` dir the middleware needs to be in `src/`

I had this problem too and I got it solved by moving middleware.ts to src/

**Comment by AntanasMisiunas** [comment]
Also having this issue on Netlify. Moving `middleware.ts` to `src` didn't help.

**Comment by nicknisi** [comment]
I haven't yet had a chance to test this but I'm wondering if there's improvements in the latest beta release. 

If you like you can test with `npm install @workos-inc/authkit-nextjs@next`.

I'll see if I can try reproducing this tomorrow.

**Comment by israelroldan** [comment]
Same here, just tested with `@workos-inc/authkit-nextjs@next` and unfortunately the issue is still there. My middleware is in src too.

Works fine on Vercel, unfortunately not on Netlify 🥲
